#!/usr/bin/env bash

#
# ~/.bashrc
#

# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# Load shared shell config
if [ -f "$HOME/.shellrc-shared" ]; then
    . "$HOME/.shellrc-shared"
fi

