#!/usr/bin/env bash

#
# ~/.shellrc-shared
#

# Environment
export TERM=xterm-256color
export WEZTERM_CONFIG_FILE="$HOME/.config/wezterm/wezterm.lua"
# export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
# export EDITOR="zed --wait"

# PATH
export PATH="$HOME/.local/bin:$PATH"

# Aliases
alias ls='ls -lah --color=auto'
alias svim='SUDO_EDITOR=nvim sudoedit'
alias grep='grep --color=auto'
alias dsf='diff-so-fancy'
