#!/usr/bin/env bash

set -e

BASE_CONFIG="meta/base.conf.yaml"
OS="$(uname -s)"

case "$OS" in
  Linux)   OS_CONFIG="meta/linux.conf.yaml" ;;
  Darwin)  OS_CONFIG="meta/macos.conf.yaml" ;;
  *)
    echo "Unsupported OS: $OS"
    exit 1
    ;;
esac

echo "Running Dotbot ($BASE_CONFIG + $OS_CONFIG)"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brewfile \
  -c "${BASE_CONFIG}" -c "$OS_CONFIG" "${@}"


