
#################
### AUTOSTART ###
#################

exec-once = systemctl --user start hyprpolkitagent

exec-once = kanshi


exec-once = mako
exec-once = waybar -c ~/.config/waybar/themes/glass/config.jsonc -s ~/.config/waybar/themes/glass/style.css

exec-once = hyprpaper
exec-once = hypridle

exec-once = pgrep -x xremap || xremap ~/.config/xremap/config.yml

# exec-once = swaybg -i ~/Photos/themes/grassy/fever-06.png -m fill

# exec-once = waybar & hyprpaper & firefox

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


# exec-once = insync start

