#############################
### ENVIRONMENT VARIABLES ###
#############################

# Variables
$terminal = wezterm
$fileManager = thunar
$menu = fuzzel
$browser = google-chrome-stable
$powermenu = ~/.config/sway/scripts/power_menu.sh# Extra env variables

# Envs
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# env = XDG_CURRENT_DESKTOP,Hyprland
# env = XDG_SESSION_TYPE,wayland
# env = XCURSOR_SIZE,24

# env = WLR_NO_HARDWARE_CURSORS,1
# env = WLR_RENDERER,gbm
# env = GBM_BACKEND,nvidia-drm
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

