##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = floating-spotify
    float = true
    center = true
    size = 1000 750
    opacity = 1 override 1 override 1 override
    match:class = floating-spotify
}

windowrule {
    name = floating-gazelle
    float = true
    center = true
    size = 1100 800
    opacity = 1 override 1 override 1 override
    match:class = floating-gazelle
}

windowrule {
    name = floating-bluetui
    float = true
    center = true
    size = 800 800
    opacity = 1 override 1 override 1 override
    match:class = floating-bluetui
}

windowrule {
    name = floating-btop
    float = true
    center = true
    size = 1300 800
    match:class = floating-btop
}

windowrule {
    name = floating-hyprmon
    float = true
    center = true
    match:class = floating-hyprmon
}

windowrule {
    name = floating-steam-friendslist
    float = true
    # center = true
    match:class = steam
    match:title = Friends List
}

windowrule {
    name = floating-save-file
    float = true
    center = true
    match:class = google-chrome
    match:title = Save File 
}

windowrule {
    name = floating-open-files
    float = true
    center = true
    match:class = xdg-desktop-portal-gtk
    match:title = Open Files 
}

windowrule {
    name = floating-open-folder
    float = true
    center = true
    match:class = xdg-desktop-portal-gtk
    match:title = Open Folder 
}

windowrule {
    name = floating-thunar-file-operation-progress
    float = true
    center = true
    match:class = thunar
    match:title = File Operation Progress 
}

windowrule {
    name = floating-pavucontrol
    float = true
    center = true
    size = 800 600
    match:class = org.pulseaudio.pavucontrol
    match:title = Volume Control
}

# windowrule {
#     name = chrome-idle-inhibit
#     idle_inhibit_fullscreen = true
#     match:class = google-chrome
# }
