# Application bindings
$terminal = uwsm-app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, L, File manager, exec, uwsm-app -- nautilus --new-window # opptatt
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER ALT, B, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER, E, Editor, exec, omarchy-launch-editor
bindd = SUPER, P, Activity, exec, $terminal -e btop # opptatt
# bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
# bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
# bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
# bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora
# bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER, D, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar/u/0/r?pli=1"
bindd = SUPER, I, Gmail, exec, omarchy-launch-webapp "https://mail.google.com/mail/u/0/#inbox"
# bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
# bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
# bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
# bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
# bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"
bind = SUPER SHIFT, S, exec, systemctl suspend

# Move current workspace to monitor (and follow it)
bind = SUPER+CTRL+SHIFT+ALT, 1, exec, hyprctl dispatch moveworkspacetomonitor $(hyprctl activeworkspace -j | jq .id) HDMI-A-1 && hyprctl dispatch focusmonitor HDMI-A-1
bind = SUPER+CTRL+SHIFT+ALT, 2, exec, hyprctl dispatch moveworkspacetomonitor $(hyprctl activeworkspace -j | jq .id) eDP-2 && hyprctl dispatch focusmonitor eDP-2

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
