general {
    col.active_border = rgb(80d4d9)
    col.inactive_border = rgb(899393)
}

$primary = rgb(80d4d9
$secondary = rgb(b1cccd
$surface = rgb(0e1415
$on_surface = rgb(dde4e4

# misc {
#     background_color = rgba(0e1415FF)
# }

# windowrule = border_color rgba(80d4d9AA) rgba(80d4d977), match:pin 1