general {
    col.active_border = rgb(286a49)
    col.inactive_border = rgb(717972)
}

$primary = rgb(286a49
$secondary = rgb(4e6355
$surface = rgb(f6fbf4
$on_surface = rgb(171d19

# misc {
#     background_color = rgba(0f1511FF)
# }

# windowrule = border_color rgba(286a49AA) rgba(286a4977), match:pin 1