general {
    col.active_border = rgb(ffc06c)
    col.inactive_border = rgb(9d8e7e)
}

$primary = rgb(ffc06c
$secondary = rgb(e2c199
$surface = rgb(17130d
$on_surface = rgb(ece1d7

# misc {
#     background_color = rgba(17130dFF)
# }

# windowrule = border_color rgba(ffc06cAA) rgba(ffc06c77), match:pin 1