splash = false
ipc = true

# preload = ~/Pictures/solarized/a_crane_with_a_light_on_top.png
# wallpaper = ,~/Pictures/solarized/a_crane_with_a_light_on_top.png


wallpaper {
    monitor = 
    path = ~/.config/current/theme/wallpaper.jpg
    fit_mode = cover
}