# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = 0
    gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master

    # opacity
}

windowrule {
  name = windowrule-1
  opacity = 0.95 0.75 1
  match:class = .*
}


    # Window appearance (optional but recommended)
windowrule {
  name = windowrule-2
  float = on
  size = (monitor_w*0.14) (monitor_h*0.08)
  move = ((monitor_w*0.43)) ((monitor_h*0.9))
  match:title = ostt
}


# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 0
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
