#!/usr/bin/env bash

# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Load shared shell config
if [ -f "$HOME/.shellrc-shared" ]; then
    . "$HOME/.shellrc-shared"
fi

# Add your own exports, aliases, and functions here.
open() { xdg-open "$@" >/dev/null; }

# Make an alias for invoking commands you use constantly
