[ids]

*
-16c0:27db

[main]

capslock = overload(control, esc)
leftcontrol = capslock

# Maps tab to tab when pressed, and fn when held with arrows
# tab = overload(hyper, tab)

# [hyper:C-M-S-A]

# Remaps the leftcontrol key to capslock


# [[app]]
# # Replace "Chromium" with the actual window class/title if needed
# title = "Chromium" 
# # Remap F1 to Ctrl+T for a new tab
# f1 = control+t 
# # Remap Alt+Left to Back (if not default)
# alt + left = back
