[ids]

*
-16c0:27db

[main]

capslock = overload(control, esc)
leftcontrol = capslock

# Maps tab to tab when pressed, and fn when held with arrows
# tab = overload(hyper, tab)

# [hyper:C-M-S-A]

# Remaps the leftcontrol key to capslock

