modmap:
  - name: Swap Ctrl to CapsLock
    device:
      not: ["MoErgo Go60 Left Keyboard", "Go60 Keyboard"]
    remap:
      LeftCtrl: CapsLock
  - name: CapsLock dual-role
    device:
      not: ["MoErgo Go60 Left Keyboard", "Go60 Keyboard"]
    remap:
      CapsLock:
        held: LeftCtrl
        alone: Esc

keymap:
  - name: Chrome tab remaps
    exact_match: true
    application:
      only: [google-chrome, chromium]
    remap:
      Ctrl-b: Ctrl-Shift-t
      Ctrl-m: Ctrl-Tab
      Ctrl-n: Ctrl-Shift-Tab
      # Ctrl-Shift-h: Ctrl-Shift-Tab
      # Ctrl-Backspace: Alt-left
      # Ctrl-Shift-Backspace: Alt-right
