keymap:
  - name: Chromium shortcuts
    application:
      only: chromium
    remap:
      C-b: C-Shift-t
      C-n: C-Shift-Tab
      C-m: C-Tab

# keymap:
#   - name: "Browser tab controls"
#     application:
#       only: [firefox, chromium, google-chrome, microsoft-edge]
#     remap:
#       C-b:
#         remap: C-S-t
#       C-n:
#         remap: C-S-Tab
#       C-m:
#         remap: C-Tab
