return {
    -- "folke/which-key.nvim",
    -- event = "VeryLazy",
    -- init = function()
    --     vim.o.timeout = true
    --     vim.o.timeoutlen = 300
    -- end,
    -- config = function()
    --     require('which-key').setup({
    --         triggers = { "<leader>", "g", "y", "a", "z", "c" },
    --         triggers_nowait = {
    --             -- marks
    --             "`",
    --             "'",
    --             "g`",
    --             "g'",
    --             -- registers
    --             '"',
    --             "<c-r>",
    --             -- spelling
    --             "z=",
    --         },
    --
    --     })
    -- end,
}
