[config]

[templates.colors]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/current/theme/colors.css'
post_hook = 'pkill -SIGUSR2 waybar && swaync-client -rs' 
#&& pkill walker && walker --gapplication-service'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.config/current/theme/wallpaper.txt'
post_hook = '~/.local/bin/sync-current-wallpaper.sh'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.chromium]
input_path = '~/.config/matugen/templates/chromium.theme'
output_path = '~/.config/current/theme/chromium.theme'
post_hook = '~/.local/bin/chromium-set-theme.sh && ~/.local/bin/chromium-set-background.sh'

#[templates.swaync]
#input_path = '~/.config/matugen/templates/colors.css'
#output_path = '~/.config/swaync/colors.css'
#post_hook = "swaync-client -rs" 

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'
post_hook = "source ~/.bashrc" 

[templates.gazelle]
input_path = '~/.config/matugen/templates/gazelle.toml'
output_path = '~/.config/gazelle/theme.toml'

[templates.spotify-player]
input_path = '~/.config/matugen/templates/spotify-player.toml'
output_path = '~/.config/spotify-player/theme.toml'

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode.json'
output_path = '~/.cache/wallust/colors.json'

[templates.vscode2]
input_path = '~/.config/matugen/templates/vscode'
output_path = '~/.cache/wallust/colors'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel-colors.ini'

[templates.wezterm]
input_path = '~/.config/matugen/templates/wezterm.lua'
output_path = '~/.config/wezterm/wezterm-colors.lua'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0.css'
output_path = '~/.config/gtk-4.0/gtk.css'
