[config]

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = "swaync-client -rs" 

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel-colors.ini'

[templates.wezterm]
input_path = '~/.config/matugen/templates/wezterm.lua'
output_path = '~/.config/wezterm/wezterm-colors.lua'

#[templates.primary]
#input_path = '~/.config/matugen/templates/primary'
#output_path = '~/.config/ml4w/colors/primary'
#
#[templates.secondary]
#input_path = '~/.config/matugen/templates/secondary'
#output_path = '~/.config/ml4w/colors/secondary'
#
#[templates.on_surface]
#input_path = '~/.config/matugen/templates/onsurface'
#output_path = '~/.config/ml4w/colors/onsurface'
